name: Send Email On Tag Creation

on:
  workflow_run:
    workflows: ["Car Assembly Pipeline"]
    types:
      - completed

jobs:
  send_email:
    if: ${{ contains(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3.8.0
        with:
          server_address: ${{ secrets.SERVER_ADDRESS }}
          server_port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: New Tag Created
          to: ${{ vars.EMAIL_RECIPIENTS }}
          from: ${{ vars.EMAIL_SENDER }}
          body: |
            Hi there,

            A new tag called **${{ github.ref_name }}** has been created in the  
            [${{ github.repository }}](https://github.com/${{ github.repository }}) repository.

            That's all for now!

            Kind regards,  
            Cat
          convert_markdown: true
