name: Car Assembly Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:  # Виклик `triggers.yml`

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout репозиторію
        uses: actions/checkout@v4

      - name: Створення папки build
        run: mkdir build

      - name: Перехід в папку та створення файлу
        run: cd build && touch build_log.txt

      - name: Додавання деталей автомобіля
        run: |
          echo "Кузов" >> build/build_log.txt
          echo "Двигун" >> build/build_log.txt
          echo "Колеса" >> build/build_log.txt
          echo "Фари" >> build/build_log.txt

      - name: Збереження артефактів
        uses: actions/upload-artifact@v4
        with:
          name: build_artifacts
          path: build/

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Завантаження артефактів
        uses: actions/download-artifact@v4
        with:
          name: build_artifacts
          path: build/

      - name: Тестування деталей
        run: |
          cd build
          grep "Кузов" build_log.txt
          grep "Двигун" build_log.txt
          grep "Колеса" build_log.txt
          grep "Фари" build_log.txt

  call-triggers:
    uses: ./.github/workflows/triggers.yml
    needs: [build, test]
