name: Triggers Workflow

on:
  workflow_call:
    inputs:
      some_input:
        description: 'Some input for this workflow'
        required: false
        default: 'default_value'
        type: string

jobs:
  send_email:
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3.8.0
        with:
          server_address: ${{ secrets.SERVER_ADDRESS }}
          server_port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: New Tag Created
          to: ${{ vars.EMAIL_RECIPIENTS }}
          from: ${{ secrets.MAIL_SENDER }}  # Add this line for the sender's email
          body: |
            Hi there,

            A new tag `${{ github.ref_name }}` has been created in the \
            [${{ github.repository }}](https://github.com/${{ github.repository }}).
