name: Triggers Workflow

on:
  # Викликається з іншого workflow
  workflow_call:
    inputs:
      some_input:
        description: 'Some input for this workflow'
        required: false
        default: 'default_value'
        type: string

  # Тригер спрацьовує при побудові GitHub Pages
  page_build:

jobs:
  send_email:
    if: ${{ contains(github.ref, 'refs/tags/') }}
    runs-on: ubuntu-latest
    steps:
      - name: Send email
        uses: dawidd6/action-send-mail@v3.8.0
        with:
          server_address: ${{ secrets.SERVER_ADDRESS }}
          server_port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.MAIL_USERNAME }}
          password: ${{ secrets.MAIL_PASSWORD }}
          subject: >
            ${{ github.event_name == 'page_build' && 'GitHub Pages Build Executed with Status of ' || 'New Tag Created' }}
            ${{ github.event.build.status || '' }}
          to: ${{ vars.EMAIL_RECIPIENTS }}
          from: ${{ vars.EMAIL_SENDER }}
          body: |
            Hi there,
            
            ${{ github.event_name == 'page_build' && format('A GitHub Pages build ran on the {0} repository. The build executed with the following result: {1}.', github.repository, github.event.build.status) || format('A new tag `{0}` has been created in the [{1}](https://github.com/{1}).', github.ref_name, github.repository) }}
            
            Please navigate to GitHub to see more.
            
            All the best,
            Cat
          convert_markdown: true
