name: Create Jira Ticket for Pull Request

on:
  # Will trigger the workflow when a new pull request is opened.
  pull_request: 
    types: opened

jobs:
  # Calls another workflow and passes in secrets and inputs
  create_ticket:
    # Pass in the path to the workflow file to call
    uses: ivankahl/github-actions-demo/.github/workflows/workflow_call_dispatch_create-jira-ticket.yml@master
    secrets:
      JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
      JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
    with:
      issuetype: Task
      summary: "Review Opened Pull Request: \
      ${{ github.event.pull_request.title }}"
